spring:
  application:
    name: consule-aware-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        healthCheckPath: /health
        healthCheckInterval: 15s
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
      tags: foo=bar, baz

server:
  port: 8090
