version: '2'
services:

  consul-aware-service-agent:
    container_name: consul-aware-service-agent
    image: library/consul:0.7.0
    volumes:
          - ./config/agent-config:/opt/consul/config
    ports:
      - "6500:8500" # cli port
      - "6600:8600" # dns port (tcp/udp)
    # network_mode: host
    command: agent -node consul-aware-service-agent -datacenter local -client 0.0.0.0 -rejoin -retry-join consul-server-ui:8301 -config-file=/opt/consul/config/consul-agent-config.json
    networks:
      - consul-server-cluster

networks:
  consul-server-cluster:
    external:
      name: consulservercluster_default